export const CURRENT_STATE_MD = `# Current State

> Auto-generated by ai-gov init. Update this file to reflect the current system state.

## System Status
- [ ] All services running
- [ ] Database migrations up to date
- [ ] CI/CD pipeline green

## Recent Changes
- Initialized AI governance structure

## Notes
_Add relevant notes about the current state here._
`;

export const ACTIVE_WORK_MD = `# Active Work

> Track work in progress, priorities, and current sprint goals.

## In Progress
- AI governance setup

## Priorities
1. _Define priorities here_

## Blocked
_Nothing currently blocked._
`;

export const KNOWN_RISKS_MD = `# Known Risks

> Document technical debt, security concerns, and operational risks.

## Security Risks
- [ ] Review .env file handling
- [ ] Audit IAM permissions

## Technical Debt
_Document technical debt items here._

## Operational Risks
_Document operational concerns here._
`;

export const ARCHITECTURE_SUMMARY_MD = `# Architecture Summary

> High-level overview of the system architecture for AI agents.

## Services
_Describe your services here._

## Data Flow
_Describe how data flows between components._

## Infrastructure
_Describe your infrastructure setup._
`;

export const NEXT_STEPS_MD = `# Next Steps

> Planned upcoming work and roadmap items.

## Short Term (this sprint)
- Complete AI governance setup
- Run first validation

## Medium Term (this quarter)
_Add medium-term goals._

## Long Term
_Add long-term vision items._
`;

export const DEPLOYMENT_STATUS_MD = `# Deployment Status

> Current state of deployments across environments.

## Environments
| Environment | Version | Status | Last Deploy |
|-------------|---------|--------|-------------|
| Development | - | Unknown | - |
| Staging | - | Unknown | - |
| Production | - | Unknown | - |

## Recent Deployments
_No deployments recorded yet._
`;

export const OPERATIONAL_NOTES_MD = `# Operational Notes

> Runtime considerations, known quirks, and operational procedures.

## Startup Order
_Document service startup dependencies._

## Common Issues
_Document frequently encountered issues and their solutions._

## Monitoring
_Document what to monitor and alerting thresholds._
`;
